# -*- coding: utf-8 -*-
"""Recommendo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WDOmWFiLfP9bbPwnp_X3ST8uHE5RgoEG
"""

!pip install pandas
!pip install llama-index
!pip install openai
!pip install langchain
!pip install python-dotenv
!pip install transformers
!pip install langchain_community
!pip install llama_index.core

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
from llama_index.core import VectorStoreIndex, Document,StorageContext,load_index_from_storage
from langchain.chat_models import ChatOpenAI
from langchain.agents import initialize_agent, Tool, AgentType
from langchain.agents import AgentExecutor
from langchain.prompts import PromptTemplate
import openai

openai.api_key = "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"  # Add your OpenAI API key here

def load_music_data(csv_path):
    data = pd.read_csv(csv_path)
    return data

def create_documents(data):
    documents = []
    for _, row in data.iterrows():
        document_text = (
            f"Title: {row['song']}\n"
            f"Artist: {row['artist']}\n"
            f"Genre: {row['genre']}\n"
            f"Popularity: {row['popularity']}\n"
        )
        documents.append(Document(text=document_text))
    return documents

def create_playlist_index(documents, index_directory="playlist_index"):
    import os
    os.makedirs(index_directory, exist_ok=True)
    index = VectorStoreIndex.from_documents(documents)
    index.storage_context.persist(persist_dir=index_directory)
    return index

def setup_playlist_agent(index_directory):

    try:
        storage_context = StorageContext.from_defaults(persist_dir=index_directory)
        index = load_index_from_storage(storage_context)
    except Exception as e:
        print(f"Error loading index: {e}")
        return None

    llm = ChatOpenAI(model="gpt-3.5-turbo", openai_api_key=openai.api_key)
    tools = [
        Tool(
            name="Playlist Generator",
            func=index.as_query_engine().query,
            description="Use this tool to generate playlists based on tags, genres, and artists."
        )
    ]

    agent = initialize_agent(
        tools,
        llm,
        agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION,
        verbose=True
    )
    return agent

def query_playlist_agent(agent, user_query):
    response = agent.run(user_query)
    return response

if __name__ == "__main__":
    csv_file_path = '/content/drive/MyDrive/playlist_generator/songs_normalize.csv'

    music_data = load_music_data(csv_file_path)

    documents = create_documents(music_data)

    index_filename = "playlist_index"
    create_playlist_index(documents, index_filename)

    agent = setup_playlist_agent(index_filename)

    print("Enter your playlist preferences (e.g., genre, artist, tags):")
    user_query = input("> ")  # E.g: "romantic song by Ed Sheeran"

    playlist = query_playlist_agent(agent, user_query)

    print("\nGenerated Playlist:")
    print(playlist)

